### ISSUE TITLE
编译完刷机发现没有helloworld

### ISSUE THREAD

**Issue by hdchieh** [LemoFire/Newifi3-K2-OpenWrt-CI#2]
Installing package 'sngrep' from telephony
Installing package 'yate' from telephony
Installing package 'luci-app-ssr-plus' from helloworld
Installing all packages from feed helloworld.
Installing package 'tcping' from helloworld
Installing package 'shadowsocks-rust' from helloworld
Installing package 'v2ray-plugin' from helloworld
Installing package 'xray-core' from helloworld
Installing package 'naiveproxy' from helloworld
Installing package 'xray-plugin' from helloworld

搜了一下发现装了 = =  但是又找不到helloworld

**Comment by UzkiS** [comment]
我有空看看，我自己很久没更新固件了，如果有问题可能是helloworld仓库更新了使用方式吧 去lean大那里看看

**Comment by UzkiS** [comment]
我有空看看，我自己很久没更新固件了，如果有问题可能是helloworld仓库更新了使用方式吧 去lean大那里看看

**Comment by hdchieh** [comment]
> 我有空看看，我自己很久没更新固件了，如果有问题可能是helloworld仓库更新了使用方式吧 去lean大那里看看

好的谢谢

**Comment by hdchieh** [comment]
> 我有空看看，我自己很久没更新固件了，如果有问题可能是helloworld仓库更新了使用方式吧 去lean大那里看看

改名了好像 叫vssr 试了一下可以了
