### ISSUE TITLE
K2未被构建

### ISSUE THREAD

**Issue by Jumpro** [LemoFire/Newifi3-K2-OpenWrt-CI#6]
K2目前未被构建，以前构建的也已经过期。。

**Comment by UzkiS** [comment]
后来k2我本地编了也不能用，建议转高恪等固件（

**Comment by Jumpro** [comment]
好的。
k2能否去掉easymesh mwan3，这样编了不知道可不可以用，如果您方便，我可来进行测试，谢谢！

**Comment by UzkiS** [comment]
我默认构建什么都不添加都无法启动，之前已经尝试过了，现在是否可行不清楚
